import { Component, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { Observable } from 'rxjs';
import { map, startWith } from 'rxjs/operators';

@Component({
  selector: 'app-team-analysis',
  templateUrl: './team-analysis.component.html',
  styleUrls: ['./team-analysis.component.scss']
})
export class TeamAnalysisComponent implements OnInit {
  dateObj: Date = new Date();
  myControl = new FormControl();
  options: Array<string> = new Array();
  filteredOptions: Observable<string[]>;
  optionsSpeed: Array<Unit> = new Array();
  monstersSelected: Array<Unit> = new Array();
  testValue: string = '25%';
  glorySpeed: Array<number> = [0, 2, 3, 5, 6, 8, 9, 11, 12, 14, 15];
  speedLead: Array<number> = [0, 10, 19, 24, 30, 33];
  glorySpeedCur: number = 0;
  speedLeadCur: number = 0;

  constructor() { }

  ngOnInit() {
    this.getMonsterList();
    this.filteredOptions = this.myControl.valueChanges
      .pipe(
        startWith(''),
        map(value => this._filter(value))
      );
  }

  private _filter(value: string): string[] {
    const filterValue = value.toLowerCase();
    return this.options.filter(option => option.toLowerCase().includes(filterValue));
  }

  getMonsterList = () => {
    let data = JSON.parse(localStorage.getItem('runeData'));
    for (let i = 0; i < data.unit_list.length; i++) {
      let tempName = this.getUnitName(data.unit_list[i].unit_master_id);
      if (!this.options.includes(tempName)) {
        this.options.push(tempName);
        this.optionsSpeed.push(data.unit_list[i]);
      }
    }
  }

  getUnitName = (id: number) => {
    for (let i = 0; i < Monster.length; i++) {
      if (id == Monster[i].com2us_id) {
        return Monster[i].name;
      }
    }
  }

  getUnitRuneSpeed = (monster: any) => {
    let total = 0;
    let swiftCount = 0;
    monster.runes.forEach(rune => {
      // spd stats
      if (rune.pri_eff[0] == 8) {
        total += rune.pri_eff[1];
      } else
        if (rune.prefix_eff[0] == 8) {
          total += rune.prefix_eff[1];
        } else {
          rune.sec_eff.forEach(sub => {
            if (sub[0] == 8) {
              total += sub[1] + sub[3];
            }
          });
        }
      // set bonus
      if (rune.set_id == 3) {
        swiftCount++;
      }
    });
    if (swiftCount > 3) {
      total += monster.spd * 0.25;
    }
    return total;
  }

  getTickRate = (speed: number) => {
    if (speed < 96) {
      return 15;
    } else if (speed < 103) {
      return 14;
    } else if (speed < 110) {
      return 13;
    } else if (speed < 120) {
      return 12;
    } else if (speed < 130) {
      return 11;
    } else if (speed < 143) {
      return 10;
    } else if (speed < 159) {
      return 9;
    } else if (speed < 179) {
      return 8;
    } else if (speed < 205) {
      return 7;
    } else if (speed < 239) {
      return 6;
    } else if (speed < 286) {
      return 5;
    } else if (speed < 358) {
      return 4;
    } else {
      return 3;
    }
  }

  getTickCalc = (speed: number, type: boolean) => {
    if (speed < 96) {
      return type ? 96 - speed : speed - 90;
    } else if (speed < 103) {
      return type ? 103 - speed : speed - 96;
    } else if (speed < 110) {
      return type ? 110 - speed : speed - 103;
    } else if (speed < 120) {
      return type ? 120 - speed : speed - 110;
    } else if (speed < 130) {
      return type ? 130 - speed : speed - 120;
    } else if (speed < 143) {
      return type ? 143 - speed : speed - 130;
    } else if (speed < 159) {
      return type ? 159 - speed : speed - 143;
    } else if (speed < 179) {
      return type ? 179 - speed : speed - 159;
    } else if (speed < 205) {
      return type ? 205 - speed : speed - 179;
    } else if (speed < 239) {
      return type ? 239 - speed : speed - 205;
    } else if (speed < 286) {
      return type ? 286 - speed : speed - 239;
    } else if (speed < 358) {
      return type ? 358 - speed : speed - 286;
    } else {
      return type ? 477 - speed : speed - 358;
    }
  }

  getTickPercent = (speed: number) => {
    if (speed < 96) {
      return 100 * (speed - 90) / (96 - 90);
    } else if (speed < 103) {
      return 100 * (speed - 96) / (103 - 96);
    } else if (speed < 110) {
      return 100 * (speed - 103) / (110 - 103);
    } else if (speed < 120) {
      return 100 * (speed - 110) / (120 - 110);
    } else if (speed < 130) {
      return 100 * (speed - 120) / (130 - 120);
    } else if (speed < 143) {
      return 100 * (speed - 133) / (143 - 130);
    } else if (speed < 159) {
      return 100 * (speed - 143) / (159 - 143);
    } else if (speed < 179) {
      return 100 * (speed - 159) / (179 - 159);
    } else if (speed < 205) {
      return 100 * (speed - 179) / (205 - 179);
    } else if (speed < 239) {
      return 100 * (speed - 205) / (239 - 205);
    } else if (speed < 286) {
      return 100 * (speed - 239) / (286 - 239);
    } else if (speed < 358) {
      return 100 * (speed - 386) / (385 - 286);
    } else {
      return 100 * (speed - 358) / (477- 385);
    }
  }

  addMonster = (text: string) => {
    this.monstersSelected.push(this.optionsSpeed[this.options.indexOf(text)]);
    // filter it by base spd
    this.sortByBaseSpd();
    this.myControl.setValue('');
  }

  setSpeedLead = (speed: number) => {
    this.speedLeadCur = speed;
  }

  setGlorySpeed = (speed: number) => {
    this.glorySpeedCur = speed;
  }

  sortByBaseSpd = () => {
    this.monstersSelected.sort((a, b) => {
      return (b.spd + b.spd * (this.glorySpeedCur + this.speedLeadCur) + this.getUnitRuneSpeed(b)) - (a.spd + a.spd * (this.glorySpeedCur + this.speedLeadCur) + this.getUnitRuneSpeed(a));
    });
  }
}

export interface Beastiary {
  com2us_id: number,
  name: string,
  element?: string
}

export interface Unit {
  accuracy: number,
  atk: number,
  con: number,
  critical_damage: number,
  critical_rate: number,
  def: number,
  homunculus: number,
  homunculus_name: string,
  resist: number,
  runes: any,
  spd: number,
  unit_id: number,
  unit_master_id: number,
}

const Monster: Array<Beastiary> = [
  { "com2us_id": 22311, "name": "Abellio", "element": "Water" },
  { "com2us_id": 22211, "name": "Abellio", "element": "Water" },
  { "com2us_id": 11913, "name": "Acasis", "element": "Wind" },
  { "com2us_id": 20912, "name": "Adrian", "element": "Fire" },
  { "com2us_id": 18811, "name": "Aegir", "element": "Water" },
  { "com2us_id": 10113, "name": "Aeilene", "element": "Wind" },
  { "com2us_id": 13714, "name": "Ahman", "element": "Light" },
  { "com2us_id": 19213, "name": "Akhamamir", "element": "Wind" },
  { "com2us_id": 17113, "name": "Akhamamir", "element": "Wind" },
  { "com2us_id": 13312, "name": "Akia", "element": "Fire" },
  { "com2us_id": 13814, "name": "Akroma", "element": "Light" },
  { "com2us_id": 21515, "name": "Alexandra", "element": "Dark" },
  { "com2us_id": 21615, "name": "Alexandra", "element": "Dark" },
  { "com2us_id": 18911, "name": "Alicia", "element": "Water" },
  { "com2us_id": 15211, "name": "Allen", "element": "Water" },
  { "com2us_id": 20414, "name": "Amarna", "element": "Light" },
  { "com2us_id": 14905, "name": "Amazon", "element": "Dark" },
  { "com2us_id": 14902, "name": "Amazon", "element": "Fire" },
  { "com2us_id": 14904, "name": "Amazon", "element": "Light" },
  { "com2us_id": 14901, "name": "Amazon", "element": "Water" },
  { "com2us_id": 14903, "name": "Amazon", "element": "Wind" },
  { "com2us_id": 20615, "name": "Amduat", "element": "Dark" },
  { "com2us_id": 21611, "name": "Amelia", "element": "Water" },
  { "com2us_id": 21511, "name": "Amelia", "element": "Water" },
  { "com2us_id": 16111, "name": "Anavel", "element": "Water" },
  { "com2us_id": 60205, "name": "Ancient Giant", "element": "Dark" },
  { "com2us_id": 60202, "name": "Ancient Giant", "element": "Fire" },
  { "com2us_id": 60204, "name": "Ancient Giant", "element": "Light" },
  { "com2us_id": 60201, "name": "Ancient Giant", "element": "Water" },
  { "com2us_id": 60203, "name": "Ancient Giant", "element": "Wind" },
  { "com2us_id": 62105, "name": "Ancient Lich King", "element": "Dark" },
  { "com2us_id": 62102, "name": "Ancient Lich King", "element": "Fire" },
  { "com2us_id": 62104, "name": "Ancient Lich King", "element": "Light" },
  { "com2us_id": 62101, "name": "Ancient Lich King", "element": "Water" },
  { "com2us_id": 62103, "name": "Ancient Lich King", "element": "Wind" },
  { "com2us_id": 11713, "name": "Anduril", "element": "Wind" },
  { "com2us_id": 60705, "name": "Angelmon", "element": "Dark" },
  { "com2us_id": 60405, "name": "Angelmon", "element": "Dark" },
  { "com2us_id": 60505, "name": "Angelmon", "element": "Dark" },
  { "com2us_id": 60605, "name": "Angelmon", "element": "Dark" },
  { "com2us_id": 14205, "name": "Angelmon", "element": "Dark" },
  { "com2us_id": 60702, "name": "Angelmon", "element": "Fire" },
  { "com2us_id": 14202, "name": "Angelmon", "element": "Fire" },
  { "com2us_id": 60502, "name": "Angelmon", "element": "Fire" },
  { "com2us_id": 60602, "name": "Angelmon", "element": "Fire" },
  { "com2us_id": 60402, "name": "Angelmon", "element": "Fire" },
  { "com2us_id": 14204, "name": "Angelmon", "element": "Light" },
  { "com2us_id": 60504, "name": "Angelmon", "element": "Light" },
  { "com2us_id": 60704, "name": "Angelmon", "element": "Light" },
  { "com2us_id": 60404, "name": "Angelmon", "element": "Light" },
  { "com2us_id": 60604, "name": "Angelmon", "element": "Light" },
  { "com2us_id": 60501, "name": "Angelmon", "element": "Water" },
  { "com2us_id": 60401, "name": "Angelmon", "element": "Water" },
  { "com2us_id": 60601, "name": "Angelmon", "element": "Water" },
  { "com2us_id": 14201, "name": "Angelmon", "element": "Water" },
  { "com2us_id": 60701, "name": "Angelmon", "element": "Water" },
  { "com2us_id": 60503, "name": "Angelmon", "element": "Wind" },
  { "com2us_id": 14203, "name": "Angelmon", "element": "Wind" },
  { "com2us_id": 60603, "name": "Angelmon", "element": "Wind" },
  { "com2us_id": 60403, "name": "Angelmon", "element": "Wind" },
  { "com2us_id": 60703, "name": "Angelmon", "element": "Wind" },
  { "com2us_id": 19312, "name": "Anne", "element": "Fire" },
  { "com2us_id": 16312, "name": "Antares", "element": "Fire" },
  { "com2us_id": 20405, "name": "Anubis", "element": "Dark" },
  { "com2us_id": 20402, "name": "Anubis", "element": "Fire" },
  { "com2us_id": 20404, "name": "Anubis", "element": "Light" },
  { "com2us_id": 40101, "name": "Anubis", "element": "Water" },
  { "com2us_id": 20401, "name": "Anubis", "element": "Water" },
  { "com2us_id": 20403, "name": "Anubis", "element": "Wind" },
  { "com2us_id": 19511, "name": "Aqcus", "element": "Water" },
  { "com2us_id": 18013, "name": "Aquila", "element": "Wind" },
  { "com2us_id": 11213, "name": "Arang", "element": "Wind" },
  { "com2us_id": 17005, "name": "Archangel", "element": "Dark" },
  { "com2us_id": 17002, "name": "Archangel", "element": "Fire" },
  { "com2us_id": 17004, "name": "Archangel", "element": "Light" },
  { "com2us_id": 17001, "name": "Archangel", "element": "Water" },
  { "com2us_id": 17003, "name": "Archangel", "element": "Wind" },
  { "com2us_id": 15413, "name": "Ardella", "element": "Wind" },
  { "com2us_id": 14713, "name": "Argen", "element": "Wind" },
  { "com2us_id": 13314, "name": "Aria", "element": "Light" },
  { "com2us_id": 17011, "name": "Ariel", "element": "Water" },
  { "com2us_id": 10414, "name": "Arkajan", "element": "Light" },
  { "com2us_id": 16212, "name": "Arnold", "element": "Fire" },
  { "com2us_id": 17014, "name": "Artamiel", "element": "Light" },
  { "com2us_id": 11815, "name": "Aschubel", "element": "Dark" },
  { "com2us_id": 19905, "name": "Assassin", "element": "Dark" },
  { "com2us_id": 19902, "name": "Assassin", "element": "Fire" },
  { "com2us_id": 19904, "name": "Assassin", "element": "Light" },
  { "com2us_id": 19901, "name": "Assassin", "element": "Water" },
  { "com2us_id": 19903, "name": "Assassin", "element": "Wind" },
  { "com2us_id": 19812, "name": "Astar", "element": "Fire" },
  { "com2us_id": 11612, "name": "Atenai", "element": "Fire" },
  { "com2us_id": 42006, "name": "Ath'taros" },
  { "com2us_id": 20411, "name": "Avaris", "element": "Water" },
  { "com2us_id": 18514, "name": "Baekdu", "element": "Light" },
  { "com2us_id": 22014, "name": "Bailey", "element": "Light" },
  { "com2us_id": 18805, "name": "Barbaric King", "element": "Dark" },
  { "com2us_id": 18802, "name": "Barbaric King", "element": "Fire" },
  { "com2us_id": 18804, "name": "Barbaric King", "element": "Light" },
  { "com2us_id": 18801, "name": "Barbaric King", "element": "Water" },
  { "com2us_id": 18803, "name": "Barbaric King", "element": "Wind" },
  { "com2us_id": 11812, "name": "Baretta", "element": "Fire" },
  { "com2us_id": 19413, "name": "Barque", "element": "Wind" },
  { "com2us_id": 19015, "name": "Basalt", "element": "Dark" },
  { "com2us_id": 20511, "name": "Bastet", "element": "Water" },
  { "com2us_id": 19005, "name": "Battle Mammoth ", "element": "Dark" },
  { "com2us_id": 19002, "name": "Battle Mammoth ", "element": "Fire" },
  { "com2us_id": 19004, "name": "Battle Mammoth ", "element": "Light" },
  { "com2us_id": 19001, "name": "Battle Mammoth ", "element": "Water" },
  { "com2us_id": 19003, "name": "Battle Mammoth ", "element": "Wind" },
  { "com2us_id": 17602, "name": "Battle Scorpion", "element": "Fire" },
  { "com2us_id": 17601, "name": "Battle Scorpion", "element": "Water" },
  { "com2us_id": 17603, "name": "Battle Scorpion", "element": "Wind" },
  { "com2us_id": 13705, "name": "Bearman", "element": "Dark" },
  { "com2us_id": 13702, "name": "Bearman", "element": "Fire" },
  { "com2us_id": 13704, "name": "Bearman", "element": "Light" },
  { "com2us_id": 13701, "name": "Bearman", "element": "Water" },
  { "com2us_id": 13703, "name": "Bearman", "element": "Wind" },
  { "com2us_id": 18505, "name": "Beast Hunter", "element": "Dark" },
  { "com2us_id": 18502, "name": "Beast Hunter", "element": "Fire" },
  { "com2us_id": 18504, "name": "Beast Hunter", "element": "Light" },
  { "com2us_id": 18501, "name": "Beast Hunter", "element": "Water" },
  { "com2us_id": 18503, "name": "Beast Hunter", "element": "Wind" },
  { "com2us_id": 17405, "name": "Beast Monk", "element": "Dark" },
  { "com2us_id": 17402, "name": "Beast Monk", "element": "Fire" },
  { "com2us_id": 17404, "name": "Beast Monk", "element": "Light" },
  { "com2us_id": 17401, "name": "Beast Monk", "element": "Water" },
  { "com2us_id": 17403, "name": "Beast Monk", "element": "Wind" },
  { "com2us_id": 21915, "name": "Belita", "element": "Dark" },
  { "com2us_id": 11014, "name": "Belladeon", "element": "Light" },
  { "com2us_id": 22312, "name": "Bellenus", "element": "Fire" },
  { "com2us_id": 22212, "name": "Bellenus", "element": "Fire" },
  { "com2us_id": 18115, "name": "Bering", "element": "Dark" },
  { "com2us_id": 11513, "name": "Bernard", "element": "Wind" },
  { "com2us_id": 17911, "name": "Beth", "element": "Water" },
  { "com2us_id": 15415, "name": "Bethony", "element": "Dark" },
  { "com2us_id": 19615, "name": "Betta", "element": "Dark" },
  { "com2us_id": 14211, "name": "Blue Angelmon", "element": "Water" },
  { "com2us_id": 18211, "name": "Blue King Angelmon", "element": "Water" },
  { "com2us_id": 22005, "name": "Boomerang Warrior", "element": "Dark" },
  { "com2us_id": 22002, "name": "Boomerang Warrior", "element": "Fire" },
  { "com2us_id": 22004, "name": "Boomerang Warrior", "element": "Light" },
  { "com2us_id": 22001, "name": "Boomerang Warrior", "element": "Water" },
  { "com2us_id": 22003, "name": "Boomerang Warrior", "element": "Wind" },
  { "com2us_id": 15605, "name": "Bounty Hunter", "element": "Dark" },
  { "com2us_id": 15602, "name": "Bounty Hunter", "element": "Fire" },
  { "com2us_id": 15604, "name": "Bounty Hunter", "element": "Light" },
  { "com2us_id": 15601, "name": "Bounty Hunter", "element": "Water" },
  { "com2us_id": 15603, "name": "Bounty Hunter", "element": "Wind" },
  { "com2us_id": 18912, "name": "Brandia", "element": "Fire" },
  { "com2us_id": 10812, "name": "Bremis", "element": "Fire" },
  { "com2us_id": 16213, "name": "Briand", "element": "Wind" },
  { "com2us_id": 19414, "name": "Brig", "element": "Light" },
  { "com2us_id": 18005, "name": "Brownie Magician", "element": "Dark" },
  { "com2us_id": 18002, "name": "Brownie Magician", "element": "Fire" },
  { "com2us_id": 18004, "name": "Brownie Magician", "element": "Light" },
  { "com2us_id": 18001, "name": "Brownie Magician", "element": "Water" },
  { "com2us_id": 18003, "name": "Brownie Magician", "element": "Wind" },
  { "com2us_id": 20812, "name": "Bulldozer", "element": "Fire" },
  { "com2us_id": 17712, "name": "Burentau", "element": "Fire" },
  { "com2us_id": 14715, "name": "Cadiz", "element": "Dark" },
  { "com2us_id": 10912, "name": "Cahule", "element": "Fire" },
  { "com2us_id": 19515, "name": "Calicus", "element": "Dark" },
  { "com2us_id": 10315, "name": "Camaryn", "element": "Dark" },
  { "com2us_id": 13811, "name": "Camilla", "element": "Water" },
  { "com2us_id": 10815, "name": "Camules", "element": "Dark" },
  { "com2us_id": 19412, "name": "Carrack", "element": "Fire" },
  { "com2us_id": 15412, "name": "Cassandra", "element": "Fire" },
  { "com2us_id": 19315, "name": "Cassie", "element": "Dark" },
  { "com2us_id": 21414, "name": "Celia", "element": "Light" },
  { "com2us_id": 14912, "name": "Ceres", "element": "Fire" },
  { "com2us_id": 13215, "name": "Chacha", "element": "Dark" },
  { "com2us_id": 21905, "name": "Chakram Dancer", "element": "Dark" },
  { "com2us_id": 21902, "name": "Chakram Dancer", "element": "Fire" },
  { "com2us_id": 21904, "name": "Chakram Dancer", "element": "Light" },
  { "com2us_id": 21901, "name": "Chakram Dancer", "element": "Water" },
  { "com2us_id": 21903, "name": "Chakram Dancer", "element": "Wind" },
  { "com2us_id": 11214, "name": "Chamie", "element": "Light" },
  { "com2us_id": 17411, "name": "Chandra", "element": "Water" },
  { "com2us_id": 44008, "name": "Chaos Beast Khi'zar Kha'jul" },
  { "com2us_id": 44009, "name": "Chaos Beast Khi'zar Kha'jul" },
  { "com2us_id": 44007, "name": "Chaos Beast Khi'zar Kha'jul" },
  { "com2us_id": 19505, "name": "Charger Shark", "element": "Dark" },
  { "com2us_id": 19502, "name": "Charger Shark", "element": "Fire" },
  { "com2us_id": 19504, "name": "Charger Shark", "element": "Light" },
  { "com2us_id": 19501, "name": "Charger Shark", "element": "Water" },
  { "com2us_id": 19503, "name": "Charger Shark", "element": "Wind" },
  { "com2us_id": 16113, "name": "Charlotte", "element": "Wind" },
  { "com2us_id": 18313, "name": "Chasun", "element": "Wind" },
  { "com2us_id": 10314, "name": "Cheryl", "element": "Light" },
  { "com2us_id": 13213, "name": "Chichi", "element": "Wind" },
  { "com2us_id": 20711, "name": "Chilling", "element": "Water" },
  { "com2us_id": 14605, "name": "Chimera", "element": "Dark" },
  { "com2us_id": 14602, "name": "Chimera", "element": "Fire" },
  { "com2us_id": 14604, "name": "Chimera", "element": "Light" },
  { "com2us_id": 14601, "name": "Chimera", "element": "Water" },
  { "com2us_id": 40703, "name": "Chimera", "element": "Wind" },
  { "com2us_id": 14603, "name": "Chimera", "element": "Wind" },
  { "com2us_id": 18612, "name": "Chiwu", "element": "Fire" },
  { "com2us_id": 15312, "name": "Chloe", "element": "Fire" },
  { "com2us_id": 16611, "name": "Chow", "element": "Water" },
  { "com2us_id": 15414, "name": "Chris", "element": "Light" },
  { "com2us_id": 19613, "name": "Cichlid", "element": "Wind" },
  { "com2us_id": 13912, "name": "Clara", "element": "Fire" },
  { "com2us_id": 10212, "name": "Cogma", "element": "Fire" },
  { "com2us_id": 12112, "name": "Colleen", "element": "Fire" },
  { "com2us_id": 16214, "name": "Conrad", "element": "Light" },
  { "com2us_id": 41401, "name": "Contaminated Dragon", "element": "Water" },
  { "com2us_id": 16513, "name": "Copper", "element": "Wind" },
  { "com2us_id": 19305, "name": "Cow Girl", "element": "Dark" },
  { "com2us_id": 19302, "name": "Cow Girl", "element": "Fire" },
  { "com2us_id": 19304, "name": "Cow Girl", "element": "Light" },
  { "com2us_id": 19301, "name": "Cow Girl", "element": "Water" },
  { "com2us_id": 19303, "name": "Cow Girl", "element": "Wind" },
  { "com2us_id": 17915, "name": "Craka", "element": "Dark" },
  { "com2us_id": 20813, "name": "Crane", "element": "Wind" },
  { "com2us_id": 20815, "name": "Crawler", "element": "Dark" },
  { "com2us_id": 10711, "name": "Dagora", "element": "Water" },
  { "com2us_id": 13713, "name": "Dagorr", "element": "Wind" },
  { "com2us_id": 10811, "name": "Daharenos", "element": "Water" },
  { "com2us_id": 21112, "name": "Daphnis ", "element": "Fire" },
  { "com2us_id": 15214, "name": "Darion", "element": "Light" },
  { "com2us_id": 14215, "name": "Dark Angelmon", "element": "Dark" },
  { "com2us_id": 43005, "name": "Dark Beast", "element": "Dark" },
  { "com2us_id": 18215, "name": "Dark King Angelmon", "element": "Dark" },
  { "com2us_id": 16205, "name": "Death Knight", "element": "Dark" },
  { "com2us_id": 16202, "name": "Death Knight", "element": "Fire" },
  { "com2us_id": 16204, "name": "Death Knight", "element": "Light" },
  { "com2us_id": 16201, "name": "Death Knight", "element": "Water" },
  { "com2us_id": 41101, "name": "Death Knight", "element": "Water" },
  { "com2us_id": 16203, "name": "Death Knight", "element": "Wind" },
  { "com2us_id": 11115, "name": "Decamaron", "element": "Dark" },
  { "com2us_id": 11613, "name": "Delphoi", "element": "Wind" },
  { "com2us_id": 20505, "name": "Desert Queen", "element": "Dark" },
  { "com2us_id": 20502, "name": "Desert Queen", "element": "Fire" },
  { "com2us_id": 20504, "name": "Desert Queen", "element": "Light" },
  { "com2us_id": 20501, "name": "Desert Queen", "element": "Water" },
  { "com2us_id": 20503, "name": "Desert Queen", "element": "Wind" },
  { "com2us_id": 21914, "name": "Deva", "element": "Light" },
  { "com2us_id": 61105, "name": "Devilmon", "element": "Dark" },
  { "com2us_id": 60805, "name": "Devilmon", "element": "Dark" },
  { "com2us_id": 15105, "name": "Devilmon", "element": "Dark" },
  { "com2us_id": 60905, "name": "Devilmon", "element": "Dark" },
  { "com2us_id": 61005, "name": "Devilmon", "element": "Dark" },
  { "com2us_id": 17815, "name": "Devinodon", "element": "Dark" },
  { "com2us_id": 21613, "name": "Diana", "element": "Wind" },
  { "com2us_id": 21513, "name": "Diana", "element": "Wind" },
  { "com2us_id": 16215, "name": "Dias", "element": "Dark" },
  { "com2us_id": 21305, "name": "Dice Magician", "element": "Dark" },
  { "com2us_id": 21302, "name": "Dice Magician", "element": "Fire" },
  { "com2us_id": 21304, "name": "Dice Magician", "element": "Light" },
  { "com2us_id": 21301, "name": "Dice Magician", "element": "Water" },
  { "com2us_id": 21303, "name": "Dice Magician", "element": "Wind" },
  { "com2us_id": 18714, "name": "Dona", "element": "Light" },
  { "com2us_id": 21014, "name": "Dova", "element": "Light" },
  { "com2us_id": 18114, "name": "Dover", "element": "Light" },
  { "com2us_id": 18012, "name": "Draco", "element": "Fire" },
  { "com2us_id": 14405, "name": "Dragon", "element": "Dark" },
  { "com2us_id": 14402, "name": "Dragon", "element": "Fire" },
  { "com2us_id": 14404, "name": "Dragon", "element": "Light" },
  { "com2us_id": 14401, "name": "Dragon", "element": "Water" },
  { "com2us_id": 14403, "name": "Dragon", "element": "Wind" },
  { "com2us_id": 16605, "name": "Dragon Knight", "element": "Dark" },
  { "com2us_id": 16602, "name": "Dragon Knight", "element": "Fire" },
  { "com2us_id": 16604, "name": "Dragon Knight", "element": "Light" },
  { "com2us_id": 16601, "name": "Dragon Knight", "element": "Water" },
  { "com2us_id": 16603, "name": "Dragon Knight", "element": "Wind" },
  { "com2us_id": 20814, "name": "Driller", "element": "Light" },
  { "com2us_id": 11715, "name": "Drogan", "element": "Dark" },
  { "com2us_id": 22205, "name": "Druid", "element": "Dark" },
  { "com2us_id": 22202, "name": "Druid", "element": "Fire" },
  { "com2us_id": 22204, "name": "Druid", "element": "Light" },
  { "com2us_id": 22201, "name": "Druid", "element": "Water" },
  { "com2us_id": 22203, "name": "Druid", "element": "Wind" },
  { "com2us_id": 17205, "name": "Drunken Master", "element": "Dark" },
  { "com2us_id": 17202, "name": "Drunken Master", "element": "Fire" },
  { "com2us_id": 17204, "name": "Drunken Master", "element": "Light" },
  { "com2us_id": 17201, "name": "Drunken Master", "element": "Water" },
  { "com2us_id": 17203, "name": "Drunken Master", "element": "Wind" },
  { "com2us_id": 22105, "name": "Dryad", "element": "Dark" },
  { "com2us_id": 22102, "name": "Dryad", "element": "Fire" },
  { "com2us_id": 22104, "name": "Dryad", "element": "Light" },
  { "com2us_id": 22101, "name": "Dryad", "element": "Water" },
  { "com2us_id": 22103, "name": "Dryad", "element": "Wind" },
  { "com2us_id": 20612, "name": "Duamutef", "element": "Fire" },
  { "com2us_id": 20715, "name": "Dusky", "element": "Dark" },
  { "com2us_id": 17713, "name": "Eintau", "element": "Wind" },
  { "com2us_id": 17013, "name": "Eladriel", "element": "Wind" },
  { "com2us_id": 21614, "name": "Eleanor", "element": "Light" },
  { "com2us_id": 21514, "name": "Eleanor", "element": "Light" },
  { "com2us_id": 10805, "name": "Elemental", "element": "Dark" },
  { "com2us_id": 10802, "name": "Elemental", "element": "Fire" },
  { "com2us_id": 10804, "name": "Elemental", "element": "Light" },
  { "com2us_id": 10801, "name": "Elemental", "element": "Water" },
  { "com2us_id": 10803, "name": "Elemental", "element": "Wind" },
  { "com2us_id": 18914, "name": "Elenoa", "element": "Light" },
  { "com2us_id": 12011, "name": "Ellena", "element": "Water" },
  { "com2us_id": 14911, "name": "Ellin", "element": "Water" },
  { "com2us_id": 11314, "name": "Elpuria", "element": "Light" },
  { "com2us_id": 17114, "name": "Elsharion", "element": "Light" },
  { "com2us_id": 19214, "name": "Elsharion", "element": "Light" },
  { "com2us_id": 10111, "name": "Elucia", "element": "Water" },
  { "com2us_id": 11714, "name": "Eludain", "element": "Light" },
  { "com2us_id": 14514, "name": "Eludia", "element": "Light" },
  { "com2us_id": 20911, "name": "Eluin", "element": "Water" },
  { "com2us_id": 20905, "name": "Elven Ranger", "element": "Dark" },
  { "com2us_id": 20902, "name": "Elven Ranger", "element": "Fire" },
  { "com2us_id": 20904, "name": "Elven Ranger", "element": "Light" },
  { "com2us_id": 20901, "name": "Elven Ranger", "element": "Water" },
  { "com2us_id": 20903, "name": "Elven Ranger", "element": "Wind" },
  { "com2us_id": 20111, "name": "Emma", "element": "Water" },
  { "com2us_id": 15305, "name": "Epikion Priest", "element": "Dark" },
  { "com2us_id": 15302, "name": "Epikion Priest", "element": "Fire" },
  { "com2us_id": 15304, "name": "Epikion Priest", "element": "Light" },
  { "com2us_id": 15301, "name": "Epikion Priest", "element": "Water" },
  { "com2us_id": 15303, "name": "Epikion Priest", "element": "Wind" },
  { "com2us_id": 11814, "name": "Eredas", "element": "Light" },
  { "com2us_id": 11313, "name": "Ermeda", "element": "Wind" },
  { "com2us_id": 20913, "name": "Erwin", "element": "Wind" },
  { "com2us_id": 14014, "name": "Eshir", "element": "Light" },
  { "com2us_id": 17913, "name": "Ethna", "element": "Wind" },
  { "com2us_id": 13914, "name": "Eva", "element": "Light" },
  { "com2us_id": 15812, "name": "Fairo", "element": "Fire" },
  { "com2us_id": 10105, "name": "Fairy", "element": "Dark" },
  { "com2us_id": 10102, "name": "Fairy", "element": "Fire" },
  { "com2us_id": 10104, "name": "Fairy", "element": "Light" },
  { "com2us_id": 10101, "name": "Fairy", "element": "Water" },
  { "com2us_id": 10103, "name": "Fairy", "element": "Wind" },
  { "com2us_id": 21105, "name": "Fairy King", "element": "Dark" },
  { "com2us_id": 21102, "name": "Fairy King", "element": "Fire" },
  { "com2us_id": 21104, "name": "Fairy King", "element": "Light" },
  { "com2us_id": 21101, "name": "Fairy King", "element": "Water" },
  { "com2us_id": 21103, "name": "Fairy King", "element": "Wind" },
  { "com2us_id": 19104, "name": "Fairy Queen", "element": "Light" },
  { "com2us_id": 16714, "name": "Fami", "element": "Light" },
  { "com2us_id": 11312, "name": "Fao", "element": "Fire" },
  { "com2us_id": 16211, "name": "Fedora", "element": "Water" },
  { "com2us_id": 17315, "name": "Fei", "element": "Dark" },
  { "com2us_id": 22114, "name": "Felleria", "element": "Light" },
  { "com2us_id": 21213, "name": "Feng Yan", "element": "Wind" },
  { "com2us_id": 17015, "name": "Fermion", "element": "Dark" },
  { "com2us_id": 13414, "name": "Figaro", "element": "Light" },
  { "com2us_id": 43002, "name": "Fire Beast ", "element": "Fire" },
  { "com2us_id": 60102, "name": "Fire Guardian", "element": "Fire" },
  { "com2us_id": 110902, "name": "Fire Minion", "element": "Fire" },
  { "com2us_id": 12302, "name": "Forest Keeper", "element": "Fire" },
  { "com2us_id": 12301, "name": "Forest Keeper", "element": "Water" },
  { "com2us_id": 12303, "name": "Forest Keeper", "element": "Wind" },
  { "com2us_id": 19114, "name": "Fran", "element": "Light" },
  { "com2us_id": 20805, "name": "Frankenstein", "element": "Dark" },
  { "com2us_id": 20802, "name": "Frankenstein", "element": "Fire" },
  { "com2us_id": 20804, "name": "Frankenstein", "element": "Light" },
  { "com2us_id": 20801, "name": "Frankenstein", "element": "Water" },
  { "com2us_id": 20803, "name": "Frankenstein", "element": "Wind" },
  { "com2us_id": 11912, "name": "Fria", "element": "Fire" },
  { "com2us_id": 19415, "name": "Frigate", "element": "Dark" },
  { "com2us_id": 16313, "name": "Fuco", "element": "Wind" },
  { "com2us_id": 10211, "name": "Fynn", "element": "Water" },
  { "com2us_id": 19411, "name": "Galleon", "element": "Water" },
  { "com2us_id": 10613, "name": "Gamir", "element": "Wind" },
  { "com2us_id": 18511, "name": "Gangchun", "element": "Water" },
  { "com2us_id": 21113, "name": "Ganymede", "element": "Wind" },
  { "com2us_id": 13512, "name": "Garo", "element": "Fire" },
  { "com2us_id": 14012, "name": "Garoche", "element": "Fire" },
  { "com2us_id": 10215, "name": "Garok", "element": "Dark" },
  { "com2us_id": 10905, "name": "Garuda", "element": "Dark" },
  { "com2us_id": 10902, "name": "Garuda", "element": "Fire" },
  { "com2us_id": 10904, "name": "Garuda", "element": "Light" },
  { "com2us_id": 10901, "name": "Garuda", "element": "Water" },
  { "com2us_id": 10903, "name": "Garuda", "element": "Wind" },
  { "com2us_id": 18014, "name": "Gemini", "element": "Light" },
  { "com2us_id": 14812, "name": "Geoffrey", "element": "Fire" },
  { "com2us_id": 12705, "name": "Ghost", "element": "Dark" },
  { "com2us_id": 12702, "name": "Ghost", "element": "Fire" },
  { "com2us_id": 12701, "name": "Ghost", "element": "Water" },
  { "com2us_id": 12703, "name": "Ghost", "element": "Wind" },
  { "com2us_id": 15715, "name": "Giana", "element": "Dark" },
  { "com2us_id": 18411, "name": "Gildong", "element": "Water" },
  { "com2us_id": 13514, "name": "Gin", "element": "Light" },
  { "com2us_id": 15915, "name": "Gina", "element": "Dark" },
  { "com2us_id": 17814, "name": "Glinodon", "element": "Light" },
  { "com2us_id": 14213, "name": "Gold Angelmon", "element": "Wind" },
  { "com2us_id": 18213, "name": "Gold King Angelmon", "element": "Wind" },
  { "com2us_id": 11405, "name": "Golem", "element": "Dark" },
  { "com2us_id": 11402, "name": "Golem", "element": "Fire" },
  { "com2us_id": 40302, "name": "Golem", "element": "Fire" },
  { "com2us_id": 11404, "name": "Golem", "element": "Light" },
  { "com2us_id": 11401, "name": "Golem", "element": "Water" },
  { "com2us_id": 11403, "name": "Golem", "element": "Wind" },
  { "com2us_id": 10715, "name": "Gorgo", "element": "Dark" },
  { "com2us_id": 19012, "name": "Granite", "element": "Fire" },
  { "com2us_id": 16315, "name": "Grego", "element": "Dark" },
  { "com2us_id": 11505, "name": "Griffon", "element": "Dark" },
  { "com2us_id": 11502, "name": "Griffon", "element": "Fire" },
  { "com2us_id": 11504, "name": "Griffon", "element": "Light" },
  { "com2us_id": 11501, "name": "Griffon", "element": "Water" },
  { "com2us_id": 11503, "name": "Griffon", "element": "Wind" },
  { "com2us_id": 16005, "name": "Grim Reaper", "element": "Dark" },
  { "com2us_id": 16002, "name": "Grim Reaper", "element": "Fire" },
  { "com2us_id": 16004, "name": "Grim Reaper", "element": "Light" },
  { "com2us_id": 16001, "name": "Grim Reaper", "element": "Water" },
  { "com2us_id": 16003, "name": "Grim Reaper", "element": "Wind" },
  { "com2us_id": 14415, "name": "Grogen", "element": "Dark" },
  { "com2us_id": 11414, "name": "Groggo", "element": "Light" },
  { "com2us_id": 17714, "name": "Grotau", "element": "Light" },
  { "com2us_id": 13711, "name": "Gruda", "element": "Water" },
  { "com2us_id": 60105, "name": "Guardian of Darkness", "element": "Dark" },
  { "com2us_id": 60104, "name": "Guardian of Light", "element": "Light" },
  { "com2us_id": 14115, "name": "Guillaume", "element": "Dark" },
  { "com2us_id": 46103, "name": "Guilles", "element": "Wind" },
  { "com2us_id": 46303, "name": "Guilles", "element": "Wind" },
  { "com2us_id": 46306, "name": "Guilles", "element": "Wind" },
  { "com2us_id": 46309, "name": "Guilles", "element": "Wind" },
  { "com2us_id": 18412, "name": "Gunpyeong", "element": "Fire" },
  { "com2us_id": 13715, "name": "Haken", "element": "Dark" },
  { "com2us_id": 16314, "name": "Halphas", "element": "Light" },
  { "com2us_id": 13515, "name": "Han", "element": "Dark" },
  { "com2us_id": 19313, "name": "Hannah", "element": "Wind" },
  { "com2us_id": 18515, "name": "Hanra", "element": "Dark" },
  { "com2us_id": 21005, "name": "Harg", "element": "Dark" },
  { "com2us_id": 21002, "name": "Harg", "element": "Fire" },
  { "com2us_id": 21004, "name": "Harg", "element": "Light" },
  { "com2us_id": 21001, "name": "Harg", "element": "Water" },
  { "com2us_id": 21003, "name": "Harg", "element": "Wind" },
  { "com2us_id": 21412, "name": "Harmonia", "element": "Fire" },
  { "com2us_id": 21405, "name": "Harp Magician", "element": "Dark" },
  { "com2us_id": 21402, "name": "Harp Magician", "element": "Fire" },
  { "com2us_id": 21404, "name": "Harp Magician", "element": "Light" },
  { "com2us_id": 21401, "name": "Harp Magician", "element": "Water" },
  { "com2us_id": 21403, "name": "Harp Magician", "element": "Wind" },
  { "com2us_id": 12105, "name": "Harpu", "element": "Dark" },
  { "com2us_id": 12102, "name": "Harpu", "element": "Fire" },
  { "com2us_id": 12104, "name": "Harpu", "element": "Light" },
  { "com2us_id": 12101, "name": "Harpu", "element": "Water" },
  { "com2us_id": 12103, "name": "Harpu", "element": "Wind" },
  { "com2us_id": 10505, "name": "Harpy", "element": "Dark" },
  { "com2us_id": 10502, "name": "Harpy", "element": "Fire" },
  { "com2us_id": 10504, "name": "Harpy", "element": "Light" },
  { "com2us_id": 10501, "name": "Harpy", "element": "Water" },
  { "com2us_id": 10503, "name": "Harpy", "element": "Wind" },
  { "com2us_id": 20513, "name": "Hathor", "element": "Wind" },
  { "com2us_id": 12815, "name": "Havana", "element": "Dark" },
  { "com2us_id": 21612, "name": "Helena", "element": "Fire" },
  { "com2us_id": 21512, "name": "Helena", "element": "Fire" },
  { "com2us_id": 10515, "name": "Hellea", "element": "Dark" },
  { "com2us_id": 10605, "name": "Hellhound", "element": "Dark" },
  { "com2us_id": 10602, "name": "Hellhound", "element": "Fire" },
  { "com2us_id": 10604, "name": "Hellhound", "element": "Light" },
  { "com2us_id": 10601, "name": "Hellhound", "element": "Water" },
  { "com2us_id": 10603, "name": "Hellhound", "element": "Wind" },
  { "com2us_id": 17905, "name": "Hell Lady", "element": "Dark" },
  { "com2us_id": 17902, "name": "Hell Lady", "element": "Fire" },
  { "com2us_id": 17904, "name": "Hell Lady", "element": "Light" },
  { "com2us_id": 17901, "name": "Hell Lady", "element": "Water" },
  { "com2us_id": 17903, "name": "Hell Lady", "element": "Wind" },
  { "com2us_id": 16011, "name": "Hemos", "element": "Water" },
  { "com2us_id": 22111, "name": "Herne", "element": "Water" },
  { "com2us_id": 12005, "name": "High Elemental", "element": "Dark" },
  { "com2us_id": 12002, "name": "High Elemental", "element": "Fire" },
  { "com2us_id": 12004, "name": "High Elemental", "element": "Light" },
  { "com2us_id": 12001, "name": "High Elemental", "element": "Water" },
  { "com2us_id": 12003, "name": "High Elemental", "element": "Wind" },
  { "com2us_id": 14913, "name": "Hina", "element": "Wind" },
  { "com2us_id": 20214, "name": "Hiro", "element": "Light" },
  { "com2us_id": 16013, "name": "Hiva", "element": "Wind" },
  { "com2us_id": 1000102, "name": "Homunculus(Attack)", "element": "Fire" },
  { "com2us_id": 1000112, "name": "Homunculus(Attack)", "element": "Fire" },
  { "com2us_id": 1000101, "name": "Homunculus(Attack)", "element": "Water" },
  { "com2us_id": 1000111, "name": "Homunculus(Attack)", "element": "Water" },
  { "com2us_id": 1000113, "name": "Homunculus(Attack)", "element": "Wind" },
  { "com2us_id": 1000103, "name": "Homunculus(Attack)", "element": "Wind" },
  { "com2us_id": 1000205, "name": "Homunculus(Support)", "element": "Dark" },
  { "com2us_id": 1000215, "name": "Homunculus(Support)", "element": "Dark" },
  { "com2us_id": 1000204, "name": "Homunculus(Support)", "element": "Light" },
  { "com2us_id": 1000214, "name": "Homunculus(Support)", "element": "Light" },
  { "com2us_id": 17312, "name": "Hong Hua", "element": "Fire" },
  { "com2us_id": 13005, "name": "Horned Frog", "element": "Dark" },
  { "com2us_id": 13002, "name": "Horned Frog", "element": "Fire" },
  { "com2us_id": 13001, "name": "Horned Frog", "element": "Water" },
  { "com2us_id": 13003, "name": "Horned Frog", "element": "Wind" },
  { "com2us_id": 20605, "name": "Horus", "element": "Dark" },
  { "com2us_id": 20602, "name": "Horus", "element": "Fire" },
  { "com2us_id": 20604, "name": "Horus", "element": "Light" },
  { "com2us_id": 20601, "name": "Horus", "element": "Water" },
  { "com2us_id": 20603, "name": "Horus", "element": "Wind" },
  { "com2us_id": 13205, "name": "Howl", "element": "Dark" },
  { "com2us_id": 13202, "name": "Howl", "element": "Fire" },
  { "com2us_id": 13204, "name": "Howl", "element": "Light" },
  { "com2us_id": 13201, "name": "Howl", "element": "Water" },
  { "com2us_id": 13203, "name": "Howl", "element": "Wind" },
  { "com2us_id": 18813, "name": "Hraesvelg", "element": "Wind" },
  { "com2us_id": 18815, "name": "Hrungnir", "element": "Dark" },
  { "com2us_id": 17213, "name": "Huan", "element": "Wind" },
  { "com2us_id": 14811, "name": "Huga", "element": "Water" },
  { "com2us_id": 15512, "name": "Hwa", "element": "Fire" },
  { "com2us_id": 18414, "name": "Hwadam", "element": "Light" },
  { "com2us_id": 18312, "name": "Hwahee", "element": "Fire" },
  { "com2us_id": 22115, "name": "Hyanes", "element": "Dark" },
  { "com2us_id": 11915, "name": "Icares", "element": "Dark" },
  { "com2us_id": 11011, "name": "Icaru", "element": "Water" },
  { "com2us_id": 11614, "name": "Icasha", "element": "Light" },
  { "com2us_id": 310306, "name": "Ice Beast" },
  { "com2us_id": 43001, "name": "Ice Beast ", "element": "Water" },
  { "com2us_id": 17105, "name": "Ifrit", "element": "Dark" },
  { "com2us_id": 19205, "name": "Ifrit", "element": "Dark" },
  { "com2us_id": 19202, "name": "Ifrit", "element": "Fire" },
  { "com2us_id": 17102, "name": "Ifrit", "element": "Fire" },
  { "com2us_id": 19204, "name": "Ifrit", "element": "Light" },
  { "com2us_id": 17104, "name": "Ifrit", "element": "Light" },
  { "com2us_id": 19201, "name": "Ifrit", "element": "Water" },
  { "com2us_id": 17101, "name": "Ifrit", "element": "Water" },
  { "com2us_id": 19203, "name": "Ifrit", "element": "Wind" },
  { "com2us_id": 17103, "name": "Ifrit", "element": "Wind" },
  { "com2us_id": 17812, "name": "Igmanodon", "element": "Fire" },
  { "com2us_id": 19512, "name": "Ignicus", "element": "Fire" },
  { "com2us_id": 20114, "name": "Illianna", "element": "Light" },
  { "com2us_id": 20613, "name": "Imesety", "element": "Wind" },
  { "com2us_id": 10205, "name": "Imp", "element": "Dark" },
  { "com2us_id": 10202, "name": "Imp", "element": "Fire" },
  { "com2us_id": 10204, "name": "Imp", "element": "Light" },
  { "com2us_id": 10201, "name": "Imp", "element": "Water" },
  { "com2us_id": 10203, "name": "Imp", "element": "Wind" },
  { "com2us_id": 15805, "name": "Imp Champion", "element": "Dark" },
  { "com2us_id": 15802, "name": "Imp Champion", "element": "Fire" },
  { "com2us_id": 15804, "name": "Imp Champion", "element": "Light" },
  { "com2us_id": 15801, "name": "Imp Champion", "element": "Water" },
  { "com2us_id": 15803, "name": "Imp Champion", "element": "Wind" },
  { "com2us_id": 20621, "name": "Imperfect Horus", "element": "Water" },
  { "com2us_id": 13422, "name": "Imperfect Joker", "element": "Fire" },
  { "com2us_id": 17323, "name": "Imperfect Kung Fu Girl", "element": "Wind" },
  { "com2us_id": 11223, "name": "Imperfect Nine-tailed Fox", "element": "Wind" },
  { "com2us_id": 13521, "name": "Imperfect Ninja", "element": "Water" },
  { "com2us_id": 13322, "name": "Imperfect Succubus", "element": "Fire" },
  { "com2us_id": 11822, "name": "Imperfect Sylph", "element": "Fire" },
  { "com2us_id": 11621, "name": "Imperfect Undine", "element": "Water" },
  { "com2us_id": 14723, "name": "Imperfect Vampire", "element": "Wind" },
  { "com2us_id": 110606, "name": "Incarnation of Greed" },
  { "com2us_id": 110306, "name": "Incarnation of Greed" },
  { "com2us_id": 110506, "name": "Incarnation of Protection" },
  { "com2us_id": 110806, "name": "Incarnation of Protection" },
  { "com2us_id": 110406, "name": "Incarnation of Vendetta" },
  { "com2us_id": 110706, "name": "Incarnation of Vendetta" },
  { "com2us_id": 21422, "name": "Incomplete Harp Magician", "element": "Fire" },
  { "com2us_id": 16921, "name": "Incomplete Samurai", "element": "Water" },
  { "com2us_id": 11705, "name": "Inferno", "element": "Dark" },
  { "com2us_id": 11702, "name": "Inferno", "element": "Fire" },
  { "com2us_id": 40602, "name": "Inferno", "element": "Fire" },
  { "com2us_id": 11704, "name": "Inferno", "element": "Light" },
  { "com2us_id": 11701, "name": "Inferno", "element": "Water" },
  { "com2us_id": 11703, "name": "Inferno", "element": "Wind" },
  { "com2us_id": 11005, "name": "Inugami", "element": "Dark" },
  { "com2us_id": 11002, "name": "Inugami", "element": "Fire" },
  { "com2us_id": 11004, "name": "Inugami", "element": "Light" },
  { "com2us_id": 11001, "name": "Inugami", "element": "Water" },
  { "com2us_id": 11003, "name": "Inugami", "element": "Wind" },
  { "com2us_id": 15314, "name": "Iona", "element": "Light" },
  { "com2us_id": 19814, "name": "Iris", "element": "Light" },
  { "com2us_id": 16512, "name": "Iron", "element": "Fire" },
  { "com2us_id": 19915, "name": "Isabelle", "element": "Dark" },
  { "com2us_id": 13315, "name": "Isael", "element": "Dark" },
  { "com2us_id": 10112, "name": "Iselia", "element": "Fire" },
  { "com2us_id": 20915, "name": "Isillen", "element": "Dark" },
  { "com2us_id": 20514, "name": "Isis", "element": "Light" },
  { "com2us_id": 20413, "name": "Iunu", "element": "Wind" },
  { "com2us_id": 13311, "name": "Izaria", "element": "Water" },
  { "com2us_id": 14515, "name": "Jaara", "element": "Dark" },
  { "com2us_id": 20215, "name": "Jackie", "element": "Dark" },
  { "com2us_id": 20705, "name": "Jack-o'-lantern", "element": "Dark" },
  { "com2us_id": 20702, "name": "Jack-o'-lantern", "element": "Fire" },
  { "com2us_id": 20704, "name": "Jack-o'-lantern", "element": "Light" },
  { "com2us_id": 20701, "name": "Jack-o'-lantern", "element": "Water" },
  { "com2us_id": 20703, "name": "Jack-o'-lantern", "element": "Wind" },
  { "com2us_id": 16614, "name": "Jager", "element": "Light" },
  { "com2us_id": 15615, "name": "Jamie", "element": "Dark" },
  { "com2us_id": 14413, "name": "Jamire", "element": "Wind" },
  { "com2us_id": 14815, "name": "Janssen", "element": "Dark" },
  { "com2us_id": 14814, "name": "Jansson", "element": "Light" },
  { "com2us_id": 14112, "name": "Jean", "element": "Fire" },
  { "com2us_id": 21814, "name": "Jeanne", "element": "Light" },
  { "com2us_id": 13412, "name": "Jojo", "element": "Fire" },
  { "com2us_id": 13405, "name": "Joker", "element": "Dark" },
  { "com2us_id": 13402, "name": "Joker", "element": "Fire" },
  { "com2us_id": 13404, "name": "Joker", "element": "Light" },
  { "com2us_id": 13401, "name": "Joker", "element": "Water" },
  { "com2us_id": 13403, "name": "Joker", "element": "Wind" },
  { "com2us_id": 21811, "name": "Josephine", "element": "Water" },
  { "com2us_id": 15215, "name": "Jubelle", "element": "Dark" },
  { "com2us_id": 14714, "name": "Julianne", "element": "Light" },
  { "com2us_id": 13911, "name": "Julie", "element": "Water" },
  { "com2us_id": 14113, "name": "Julien", "element": "Wind" },
  { "com2us_id": 14015, "name": "Jultan", "element": "Dark" },
  { "com2us_id": 12015, "name": "Jumaline", "element": "Dark" },
  { "com2us_id": 16912, "name": "Jun", "element": "Fire" },
  { "com2us_id": 15712, "name": "Juno", "element": "Fire" },
  { "com2us_id": 10514, "name": "Kabilla", "element": "Light" },
  { "com2us_id": 10311, "name": "Kacey", "element": "Water" },
  { "com2us_id": 12012, "name": "Kahli", "element": "Fire" },
  { "com2us_id": 11511, "name": "Kahn", "element": "Water" },
  { "com2us_id": 15212, "name": "Kai'en", "element": "Fire" },
  { "com2us_id": 11111, "name": "Kaimann", "element": "Water" },
  { "com2us_id": 16913, "name": "Kaito", "element": "Wind" },
  { "com2us_id": 17715, "name": "Kamatau", "element": "Dark" },
  { "com2us_id": 11215, "name": "Kamiya", "element": "Dark" },
  { "com2us_id": 20315, "name": "Karakum", "element": "Dark" },
  { "com2us_id": 20015, "name": "Karl", "element": "Dark" },
  { "com2us_id": 13813, "name": "Katarina", "element": "Wind" },
  { "com2us_id": 16911, "name": "Kaz", "element": "Water" },
  { "com2us_id": 62004, "name": "Keeper of Magic", "element": "Light" },
  { "com2us_id": 17811, "name": "Kernodon", "element": "Water" },
  { "com2us_id": 20412, "name": "Khmun", "element": "Fire" },
  { "com2us_id": 18205, "name": "King Angelmon", "element": "Dark" },
  { "com2us_id": 18202, "name": "King Angelmon", "element": "Fire" },
  { "com2us_id": 18204, "name": "King Angelmon", "element": "Light" },
  { "com2us_id": 18201, "name": "King Angelmon", "element": "Water" },
  { "com2us_id": 18203, "name": "King Angelmon", "element": "Wind" },
  { "com2us_id": 18105, "name": "Kobold Bomber", "element": "Dark" },
  { "com2us_id": 18102, "name": "Kobold Bomber", "element": "Fire" },
  { "com2us_id": 18104, "name": "Kobold Bomber", "element": "Light" },
  { "com2us_id": 18101, "name": "Kobold Bomber", "element": "Water" },
  { "com2us_id": 18103, "name": "Kobold Bomber", "element": "Wind" },
  { "com2us_id": 10911, "name": "Konamiya", "element": "Water" },
  { "com2us_id": 18015, "name": "Korona", "element": "Dark" },
  { "com2us_id": 46308, "name": "Kotos", "element": "Fire" },
  { "com2us_id": 46302, "name": "Kotos", "element": "Fire" },
  { "com2us_id": 46102, "name": "Kotos", "element": "Fire" },
  { "com2us_id": 46305, "name": "Kotos", "element": "Fire" },
  { "com2us_id": 11112, "name": "Krakdon", "element": "Fire" },
  { "com2us_id": 11015, "name": "Kro", "element": "Dark" },
  { "com2us_id": 21015, "name": "Kroa", "element": "Dark" },
  { "com2us_id": 11412, "name": "Kugo", "element": "Fire" },
  { "com2us_id": 11411, "name": "Kuhn", "element": "Water" },
  { "com2us_id": 10415, "name": "Kumae", "element": "Dark" },
  { "com2us_id": 17412, "name": "Kumar", "element": "Fire" },
  { "com2us_id": 18715, "name": "Kuna", "element": "Dark" },
  { "com2us_id": 10411, "name": "Kunda", "element": "Water" },
  { "com2us_id": 13712, "name": "Kungen", "element": "Fire" },
  { "com2us_id": 17305, "name": "Kung Fu Girl", "element": "Dark" },
  { "com2us_id": 17302, "name": "Kung Fu Girl", "element": "Fire" },
  { "com2us_id": 17304, "name": "Kung Fu Girl", "element": "Light" },
  { "com2us_id": 17301, "name": "Kung Fu Girl", "element": "Water" },
  { "com2us_id": 17303, "name": "Kung Fu Girl", "element": "Wind" },
  { "com2us_id": 14613, "name": "Lagmaron", "element": "Wind" },
  { "com2us_id": 16612, "name": "Laika", "element": "Fire" },
  { "com2us_id": 15714, "name": "Laima", "element": "Light" },
  { "com2us_id": 13212, "name": "Lala", "element": "Fire" },
  { "com2us_id": 12812, "name": "Lamor", "element": "Fire" },
  { "com2us_id": 19815, "name": "Lanett", "element": "Dark" },
  { "com2us_id": 19811, "name": "Lapis", "element": "Water" },
  { "com2us_id": 60305, "name": "Legendary Dragon", "element": "Dark" },
  { "com2us_id": 60302, "name": "Legendary Dragon", "element": "Fire" },
  { "com2us_id": 60304, "name": "Legendary Dragon", "element": "Light" },
  { "com2us_id": 60301, "name": "Legendary Dragon", "element": "Water" },
  { "com2us_id": 60303, "name": "Legendary Dragon", "element": "Wind" },
  { "com2us_id": 16613, "name": "Leo", "element": "Wind" },
  { "com2us_id": 21815, "name": "Leona", "element": "Dark" },
  { "com2us_id": 46101, "name": "Leos", "element": "Water" },
  { "com2us_id": 46304, "name": "Leos", "element": "Water" },
  { "com2us_id": 46301, "name": "Leos", "element": "Water" },
  { "com2us_id": 46307, "name": "Leos", "element": "Water" },
  { "com2us_id": 19912, "name": "Lexy", "element": "Fire" },
  { "com2us_id": 16305, "name": "Lich", "element": "Dark" },
  { "com2us_id": 16302, "name": "Lich", "element": "Fire" },
  { "com2us_id": 41202, "name": "Lich", "element": "Fire" },
  { "com2us_id": 16304, "name": "Lich", "element": "Light" },
  { "com2us_id": 16301, "name": "Lich", "element": "Water" },
  { "com2us_id": 16303, "name": "Lich", "element": "Wind" },
  { "com2us_id": 13415, "name": "Liebli", "element": "Dark" },
  { "com2us_id": 14711, "name": "Liesel", "element": "Water" },
  { "com2us_id": 43004, "name": "Light Beast", "element": "Light" },
  { "com2us_id": 15914, "name": "Linda", "element": "Light" },
  { "com2us_id": 10913, "name": "Lindermen", "element": "Wind" },
  { "com2us_id": 17313, "name": "Ling Ling", "element": "Wind" },
  { "com2us_id": 20112, "name": "Lisa", "element": "Fire" },
  { "com2us_id": 17314, "name": "Liu Mei", "element": "Light" },
  { "com2us_id": 16505, "name": "Living Armor", "element": "Dark" },
  { "com2us_id": 16502, "name": "Living Armor", "element": "Fire" },
  { "com2us_id": 16504, "name": "Living Armor", "element": "Light" },
  { "com2us_id": 16501, "name": "Living Armor", "element": "Water" },
  { "com2us_id": 16503, "name": "Living Armor", "element": "Wind" },
  { "com2us_id": 17805, "name": "Lizardman", "element": "Dark" },
  { "com2us_id": 17802, "name": "Lizardman", "element": "Fire" },
  { "com2us_id": 17804, "name": "Lizardman", "element": "Light" },
  { "com2us_id": 17801, "name": "Lizardman", "element": "Water" },
  { "com2us_id": 17803, "name": "Lizardman", "element": "Wind" },
  { "com2us_id": 20213, "name": "Lo", "element": "Wind" },
  { "com2us_id": 20013, "name": "Logan", "element": "Wind" },
  { "com2us_id": 15815, "name": "Loque", "element": "Dark" },
  { "com2us_id": 16114, "name": "Lora", "element": "Light" },
  { "com2us_id": 19314, "name": "Loren", "element": "Light" },
  { "com2us_id": 14114, "name": "Louis", "element": "Light" },
  { "com2us_id": 21813, "name": "Louise", "element": "Wind" },
  { "com2us_id": 12805, "name": "Low Elemental", "element": "Dark" },
  { "com2us_id": 12802, "name": "Low Elemental", "element": "Fire" },
  { "com2us_id": 12804, "name": "Low Elemental", "element": "Light" },
  { "com2us_id": 12801, "name": "Low Elemental", "element": "Water" },
  { "com2us_id": 12803, "name": "Low Elemental", "element": "Wind" },
  { "com2us_id": 20211, "name": "Luan", "element": "Water" },
  { "com2us_id": 20014, "name": "Lucas", "element": "Light" },
  { "com2us_id": 10512, "name": "Lucasha", "element": "Fire" },
  { "com2us_id": 20914, "name": "Lucien", "element": "Light" },
  { "com2us_id": 21312, "name": "Ludo", "element": "Fire" },
  { "com2us_id": 14111, "name": "Luer", "element": "Water" },
  { "com2us_id": 11113, "name": "Lukan", "element": "Wind" },
  { "com2us_id": 13211, "name": "Lulu", "element": "Water" },
  { "com2us_id": 11911, "name": "Lumirecia", "element": "Water" },
  { "com2us_id": 13915, "name": "Luna", "element": "Dark" },
  { "com2us_id": 19813, "name": "Lupinus", "element": "Wind" },
  { "com2us_id": 10714, "name": "Lusha", "element": "Light" },
  { "com2us_id": 13413, "name": "Lushen", "element": "Wind" },
  { "com2us_id": 18915, "name": "Lydia", "element": "Dark" },
  { "com2us_id": 14914, "name": "Lyn", "element": "Light" },
  { "com2us_id": 42106, "name": "Lyrith" },
  { "com2us_id": 42206, "name": "Lyrith" },
  { "com2us_id": 11415, "name": "Maggi", "element": "Dark" },
  { "com2us_id": 15405, "name": "Magical Archer", "element": "Dark" },
  { "com2us_id": 15402, "name": "Magical Archer", "element": "Fire" },
  { "com2us_id": 16704, "name": "Magical Archer", "element": "Light" },
  { "com2us_id": 15404, "name": "Magical Archer", "element": "Light" },
  { "com2us_id": 15401, "name": "Magical Archer", "element": "Water" },
  { "com2us_id": 15403, "name": "Magical Archer", "element": "Wind" },
  { "com2us_id": 19805, "name": "Magic Knight", "element": "Dark" },
  { "com2us_id": 19802, "name": "Magic Knight", "element": "Fire" },
  { "com2us_id": 19804, "name": "Magic Knight", "element": "Light" },
  { "com2us_id": 19801, "name": "Magic Knight", "element": "Water" },
  { "com2us_id": 19803, "name": "Magic Knight", "element": "Wind" },
  { "com2us_id": 18111, "name": "Malaka", "element": "Water" },
  { "com2us_id": 19715, "name": "Manannan", "element": "Dark" },
  { "com2us_id": 12502, "name": "Maned Boar", "element": "Fire" },
  { "com2us_id": 12501, "name": "Maned Boar", "element": "Water" },
  { "com2us_id": 12503, "name": "Maned Boar", "element": "Wind" },
  { "com2us_id": 11315, "name": "Mantura", "element": "Dark" },
  { "com2us_id": 17211, "name": "Mao", "element": "Water" },
  { "com2us_id": 14915, "name": "Mara", "element": "Dark" },
  { "com2us_id": 19014, "name": "Marble", "element": "Light" },
  { "com2us_id": 20205, "name": "Martial Artist", "element": "Dark" },
  { "com2us_id": 20202, "name": "Martial Artist", "element": "Fire" },
  { "com2us_id": 20204, "name": "Martial Artist", "element": "Light" },
  { "com2us_id": 20201, "name": "Martial Artist", "element": "Water" },
  { "com2us_id": 20203, "name": "Martial Artist", "element": "Wind" },
  { "com2us_id": 15005, "name": "Martial Cat", "element": "Dark" },
  { "com2us_id": 15002, "name": "Martial Cat", "element": "Fire" },
  { "com2us_id": 15004, "name": "Martial Cat", "element": "Light" },
  { "com2us_id": 15001, "name": "Martial Cat", "element": "Water" },
  { "com2us_id": 15003, "name": "Martial Cat", "element": "Wind" },
  { "com2us_id": 22015, "name": "Martina", "element": "Dark" },
  { "com2us_id": 22012, "name": "Maruna", "element": "Fire" },
  { "com2us_id": 18713, "name": "Mav", "element": "Wind" },
  { "com2us_id": 15911, "name": "Megan", "element": "Water" },
  { "com2us_id": 15012, "name": "Mei", "element": "Fire" },
  { "com2us_id": 16812, "name": "Mei Hou Wang", "element": "Fire" },
  { "com2us_id": 21913, "name": "Melissa", "element": "Wind" },
  { "com2us_id": 22113, "name": "Mellia", "element": "Wind" },
  { "com2us_id": 19605, "name": "Mermaid", "element": "Dark" },
  { "com2us_id": 19602, "name": "Mermaid", "element": "Fire" },
  { "com2us_id": 19604, "name": "Mermaid", "element": "Light" },
  { "com2us_id": 19601, "name": "Mermaid", "element": "Water" },
  { "com2us_id": 19603, "name": "Mermaid", "element": "Wind" },
  { "com2us_id": 15313, "name": "Michelle", "element": "Wind" },
  { "com2us_id": 11914, "name": "Mihael", "element": "Light" },
  { "com2us_id": 15015, "name": "Miho", "element": "Dark" },
  { "com2us_id": 18311, "name": "Mihyang", "element": "Water" },
  { "com2us_id": 11611, "name": "Mikene", "element": "Water" },
  { "com2us_id": 12905, "name": "Mimick", "element": "Dark" },
  { "com2us_id": 12902, "name": "Mimick", "element": "Fire" },
  { "com2us_id": 12901, "name": "Mimick", "element": "Water" },
  { "com2us_id": 12903, "name": "Mimick", "element": "Wind" },
  { "com2us_id": 18814, "name": "Mimirr", "element": "Light" },
  { "com2us_id": 15011, "name": "Mina", "element": "Water" },
  { "com2us_id": 17705, "name": "Minotauros", "element": "Dark" },
  { "com2us_id": 17702, "name": "Minotauros", "element": "Fire" },
  { "com2us_id": 17704, "name": "Minotauros", "element": "Light" },
  { "com2us_id": 17701, "name": "Minotauros", "element": "Water" },
  { "com2us_id": 17703, "name": "Minotauros", "element": "Wind" },
  { "com2us_id": 17502, "name": "Mischievous Bat", "element": "Fire" },
  { "com2us_id": 17501, "name": "Mischievous Bat", "element": "Water" },
  { "com2us_id": 17503, "name": "Mischievous Bat", "element": "Wind" },
  { "com2us_id": 20714, "name": "Misty", "element": "Light" },
  { "com2us_id": 21215, "name": "Mi Ying", "element": "Dark" },
  { "com2us_id": 19614, "name": "Molly", "element": "Light" },
  { "com2us_id": 21211, "name": "Mo Long", "element": "Water" },
  { "com2us_id": 16805, "name": "Monkey King", "element": "Dark" },
  { "com2us_id": 16802, "name": "Monkey King", "element": "Fire" },
  { "com2us_id": 16804, "name": "Monkey King", "element": "Light" },
  { "com2us_id": 16801, "name": "Monkey King", "element": "Water" },
  { "com2us_id": 16803, "name": "Monkey King", "element": "Wind" },
  { "com2us_id": 12605, "name": "Monster Flower", "element": "Dark" },
  { "com2us_id": 12602, "name": "Monster Flower", "element": "Fire" },
  { "com2us_id": 12601, "name": "Monster Flower", "element": "Water" },
  { "com2us_id": 12603, "name": "Monster Flower", "element": "Wind" },
  { "com2us_id": 21315, "name": "Monte", "element": "Dark" },
  { "com2us_id": 12013, "name": "Moria", "element": "Wind" },
  { "com2us_id": 21313, "name": "Morris", "element": "Wind" },
  { "com2us_id": 20305, "name": "Mummy", "element": "Dark" },
  { "com2us_id": 20302, "name": "Mummy", "element": "Fire" },
  { "com2us_id": 20304, "name": "Mummy", "element": "Light" },
  { "com2us_id": 20301, "name": "Mummy", "element": "Water" },
  { "com2us_id": 20303, "name": "Mummy", "element": "Wind" },
  { "com2us_id": 12402, "name": "Mushroom", "element": "Fire" },
  { "com2us_id": 12401, "name": "Mushroom", "element": "Water" },
  { "com2us_id": 12403, "name": "Mushroom", "element": "Wind" },
  { "com2us_id": 15905, "name": "Mystic Witch", "element": "Dark" },
  { "com2us_id": 15902, "name": "Mystic Witch", "element": "Fire" },
  { "com2us_id": 15904, "name": "Mystic Witch", "element": "Light" },
  { "com2us_id": 15901, "name": "Mystic Witch", "element": "Water" },
  { "com2us_id": 15903, "name": "Mystic Witch", "element": "Wind" },
  { "com2us_id": 18712, "name": "Naki", "element": "Fire" },
  { "com2us_id": 20313, "name": "Namib", "element": "Wind" },
  { "com2us_id": 18512, "name": "Nangrim", "element": "Fire" },
  { "com2us_id": 15013, "name": "Naomi", "element": "Wind" },
  { "com2us_id": 19914, "name": "Natalie", "element": "Light" },
  { "com2us_id": 10114, "name": "Neal", "element": "Light" },
  { "com2us_id": 20105, "name": "Neostone Agent", "element": "Dark" },
  { "com2us_id": 20102, "name": "Neostone Agent", "element": "Fire" },
  { "com2us_id": 20104, "name": "Neostone Agent", "element": "Light" },
  { "com2us_id": 20101, "name": "Neostone Agent", "element": "Water" },
  { "com2us_id": 20103, "name": "Neostone Agent", "element": "Wind" },
  { "com2us_id": 20005, "name": "Neostone Fighter", "element": "Dark" },
  { "com2us_id": 20002, "name": "Neostone Fighter", "element": "Fire" },
  { "com2us_id": 20004, "name": "Neostone Fighter", "element": "Light" },
  { "com2us_id": 20001, "name": "Neostone Fighter", "element": "Water" },
  { "com2us_id": 20003, "name": "Neostone Fighter", "element": "Wind" },
  { "com2us_id": 20515, "name": "Nephthys", "element": "Dark" },
  { "com2us_id": 16511, "name": "Nickel", "element": "Water" },
  { "com2us_id": 16115, "name": "Nicki", "element": "Dark" },
  { "com2us_id": 18614, "name": "Nigong", "element": "Light" },
  { "com2us_id": 11205, "name": "Nine-tailed Fox", "element": "Dark" },
  { "com2us_id": 11202, "name": "Nine-tailed Fox", "element": "Fire" },
  { "com2us_id": 11204, "name": "Nine-tailed Fox", "element": "Light" },
  { "com2us_id": 11201, "name": "Nine-tailed Fox", "element": "Water" },
  { "com2us_id": 11203, "name": "Nine-tailed Fox", "element": "Wind" },
  { "com2us_id": 13505, "name": "Ninja", "element": "Dark" },
  { "com2us_id": 13502, "name": "Ninja", "element": "Fire" },
  { "com2us_id": 13504, "name": "Ninja", "element": "Light" },
  { "com2us_id": 13501, "name": "Ninja", "element": "Water" },
  { "com2us_id": 13503, "name": "Ninja", "element": "Wind" },
  { "com2us_id": 22112, "name": "Nisha", "element": "Fire" },
  { "com2us_id": 20311, "name": "Nubia", "element": "Water" },
  { "com2us_id": 21115, "name": "Nyx", "element": "Dark" },
  { "com2us_id": 21114, "name": "Oberon", "element": "Light" },
  { "com2us_id": 16105, "name": "Occult Girl", "element": "Dark" },
  { "com2us_id": 16102, "name": "Occult Girl", "element": "Fire" },
  { "com2us_id": 16104, "name": "Occult Girl", "element": "Light" },
  { "com2us_id": 16101, "name": "Occult Girl", "element": "Water" },
  { "com2us_id": 16103, "name": "Occult Girl", "element": "Wind" },
  { "com2us_id": 19712, "name": "Okeanos", "element": "Fire" },
  { "com2us_id": 20113, "name": "Olivia", "element": "Wind" },
  { "com2us_id": 19013, "name": "Olivine", "element": "Wind" },
  { "com2us_id": 21812, "name": "Ophilia", "element": "Fire" },
  { "com2us_id": 15705, "name": "Oracle", "element": "Dark" },
  { "com2us_id": 15702, "name": "Oracle", "element": "Fire" },
  { "com2us_id": 15704, "name": "Oracle", "element": "Light" },
  { "com2us_id": 15701, "name": "Oracle", "element": "Water" },
  { "com2us_id": 15703, "name": "Oracle", "element": "Wind" },
  { "com2us_id": 18011, "name": "Orion", "element": "Water" },
  { "com2us_id": 13513, "name": "Orochi", "element": "Wind" },
  { "com2us_id": 41006, "name": "Otherworldly Dragon" },
  { "com2us_id": 21805, "name": "Paladin", "element": "Dark" },
  { "com2us_id": 21802, "name": "Paladin", "element": "Fire" },
  { "com2us_id": 21804, "name": "Paladin", "element": "Light" },
  { "com2us_id": 21801, "name": "Paladin", "element": "Water" },
  { "com2us_id": 21803, "name": "Paladin", "element": "Wind" },
  { "com2us_id": 21205, "name": "Panda Warrior", "element": "Dark" },
  { "com2us_id": 21202, "name": "Panda Warrior", "element": "Fire" },
  { "com2us_id": 21204, "name": "Panda Warrior", "element": "Light" },
  { "com2us_id": 21201, "name": "Panda Warrior", "element": "Water" },
  { "com2us_id": 21203, "name": "Panda Warrior", "element": "Wind" },
  { "com2us_id": 15514, "name": "Pang", "element": "Light" },
  { "com2us_id": 22315, "name": "Pater", "element": "Dark" },
  { "com2us_id": 22215, "name": "Pater", "element": "Dark" },
  { "com2us_id": 18705, "name": "Penguin Knight", "element": "Dark" },
  { "com2us_id": 18702, "name": "Penguin Knight", "element": "Fire" },
  { "com2us_id": 18704, "name": "Penguin Knight", "element": "Light" },
  { "com2us_id": 18701, "name": "Penguin Knight", "element": "Water" },
  { "com2us_id": 18703, "name": "Penguin Knight", "element": "Wind" },
  { "com2us_id": 14512, "name": "Perna", "element": "Fire" },
  { "com2us_id": 14105, "name": "Phantom Thief", "element": "Dark" },
  { "com2us_id": 14102, "name": "Phantom Thief", "element": "Fire" },
  { "com2us_id": 14104, "name": "Phantom Thief", "element": "Light" },
  { "com2us_id": 14101, "name": "Phantom Thief", "element": "Water" },
  { "com2us_id": 14103, "name": "Phantom Thief", "element": "Wind" },
  { "com2us_id": 14505, "name": "Phoenix", "element": "Dark" },
  { "com2us_id": 14502, "name": "Phoenix", "element": "Fire" },
  { "com2us_id": 14504, "name": "Phoenix", "element": "Light" },
  { "com2us_id": 40201, "name": "Phoenix", "element": "Water" },
  { "com2us_id": 14501, "name": "Phoenix", "element": "Water" },
  { "com2us_id": 14503, "name": "Phoenix", "element": "Wind" },
  { "com2us_id": 13905, "name": "Pierret", "element": "Dark" },
  { "com2us_id": 13902, "name": "Pierret", "element": "Fire" },
  { "com2us_id": 13904, "name": "Pierret", "element": "Light" },
  { "com2us_id": 13901, "name": "Pierret", "element": "Water" },
  { "com2us_id": 13903, "name": "Pierret", "element": "Wind" },
  { "com2us_id": 15813, "name": "Pigma", "element": "Wind" },
  { "com2us_id": 18605, "name": "Pioneer", "element": "Dark" },
  { "com2us_id": 18602, "name": "Pioneer", "element": "Fire" },
  { "com2us_id": 18604, "name": "Pioneer", "element": "Light" },
  { "com2us_id": 18601, "name": "Pioneer", "element": "Water" },
  { "com2us_id": 18603, "name": "Pioneer", "element": "Wind" },
  { "com2us_id": 19405, "name": "Pirate Captain", "element": "Dark" },
  { "com2us_id": 19402, "name": "Pirate Captain", "element": "Fire" },
  { "com2us_id": 19404, "name": "Pirate Captain", "element": "Light" },
  { "com2us_id": 19401, "name": "Pirate Captain", "element": "Water" },
  { "com2us_id": 19403, "name": "Pirate Captain", "element": "Wind" },
  { "com2us_id": 10305, "name": "Pixie", "element": "Dark" },
  { "com2us_id": 10302, "name": "Pixie", "element": "Fire" },
  { "com2us_id": 10304, "name": "Pixie", "element": "Light" },
  { "com2us_id": 10301, "name": "Pixie", "element": "Water" },
  { "com2us_id": 10303, "name": "Pixie", "element": "Wind" },
  { "com2us_id": 19612, "name": "Platy", "element": "Fire" },
  { "com2us_id": 18905, "name": "Polar Queen", "element": "Dark" },
  { "com2us_id": 18902, "name": "Polar Queen", "element": "Fire" },
  { "com2us_id": 18904, "name": "Polar Queen", "element": "Light" },
  { "com2us_id": 18901, "name": "Polar Queen", "element": "Water" },
  { "com2us_id": 18903, "name": "Polar Queen", "element": "Wind" },
  { "com2us_id": 19714, "name": "Pontos", "element": "Light" },
  { "com2us_id": 19711, "name": "Poseidon", "element": "Water" },
  { "com2us_id": 15711, "name": "Praha", "element": "Water" },
  { "com2us_id": 10513, "name": "Prilea", "element": "Wind" },
  { "com2us_id": 10814, "name": "Priz", "element": "Light" },
  { "com2us_id": 16014, "name": "Prom", "element": "Light" },
  { "com2us_id": 21111, "name": "Psamathe", "element": "Water" },
  { "com2us_id": 18613, "name": "Pungbaek", "element": "Wind" },
  { "com2us_id": 11711, "name": "Purian", "element": "Water" },
  { "com2us_id": 20611, "name": "Qebehsenuef", "element": "Water" },
  { "com2us_id": 16814, "name": "Qitian Dasheng", "element": "Light" },
  { "com2us_id": 21012, "name": "Racuni", "element": "Fire" },
  { "com2us_id": 16615, "name": "Ragdoll", "element": "Dark" },
  { "com2us_id": 11413, "name": "Ragion", "element": "Wind" },
  { "com2us_id": 17415, "name": "Rahul", "element": "Dark" },
  { "com2us_id": 14314, "name": "Rainbowmon", "element": "Light" },
  { "com2us_id": 61104, "name": "Rainbowmon", "element": "Light" },
  { "com2us_id": 60904, "name": "Rainbowmon", "element": "Light" },
  { "com2us_id": 60804, "name": "Rainbowmon", "element": "Light" },
  { "com2us_id": 61004, "name": "Rainbowmon", "element": "Light" },
  { "com2us_id": 10413, "name": "Rakaja", "element": "Wind" },
  { "com2us_id": 14612, "name": "Rakan", "element": "Fire" },
  { "com2us_id": 17912, "name": "Raki", "element": "Fire" },
  { "com2us_id": 15505, "name": "Rakshasa", "element": "Dark" },
  { "com2us_id": 15502, "name": "Rakshasa", "element": "Fire" },
  { "com2us_id": 15504, "name": "Rakshasa", "element": "Light" },
  { "com2us_id": 15501, "name": "Rakshasa", "element": "Water" },
  { "com2us_id": 15503, "name": "Rakshasa", "element": "Wind" },
  { "com2us_id": 10213, "name": "Ralph", "element": "Wind" },
  { "com2us_id": 10713, "name": "Ramagos", "element": "Wind" },
  { "com2us_id": 11013, "name": "Ramahan", "element": "Wind" },
  { "com2us_id": 10511, "name": "Ramira", "element": "Water" },
  { "com2us_id": 15515, "name": "Ran", "element": "Dark" },
  { "com2us_id": 15612, "name": "Randy", "element": "Fire" },
  { "com2us_id": 11012, "name": "Raoq", "element": "Fire" },
  { "com2us_id": 15315, "name": "Rasheed", "element": "Dark" },
  { "com2us_id": 21013, "name": "Raviti", "element": "Wind" },
  { "com2us_id": 15912, "name": "Rebecca", "element": "Fire" },
  { "com2us_id": 14212, "name": "Red Angelmon", "element": "Fire" },
  { "com2us_id": 18212, "name": "Red King Angelmon", "element": "Fire" },
  { "com2us_id": 41303, "name": "Remains Guardian", "element": "Wind" },
  { "com2us_id": 21011, "name": "Remy", "element": "Water" },
  { "com2us_id": 21311, "name": "Reno", "element": "Water" },
  { "com2us_id": 16112, "name": "Rica", "element": "Fire" },
  { "com2us_id": 16311, "name": "Rigel", "element": "Water" },
  { "com2us_id": 15311, "name": "Rina", "element": "Water" },
  { "com2us_id": 17413, "name": "Ritesh", "element": "Wind" },
  { "com2us_id": 10915, "name": "Rizak", "element": "Dark" },
  { "com2us_id": 15613, "name": "Roger", "element": "Wind" },
  { "com2us_id": 15213, "name": "Roid", "element": "Wind" },
  { "com2us_id": 19514, "name": "Rumicus", "element": "Light" },
  { "com2us_id": 20011, "name": "Ryan", "element": "Water" },
  { "com2us_id": 22011, "name": "Sabrina", "element": "Water" },
  { "com2us_id": 20314, "name": "Sahara", "element": "Light" },
  { "com2us_id": 11105, "name": "Salamander", "element": "Dark" },
  { "com2us_id": 11102, "name": "Salamander", "element": "Fire" },
  { "com2us_id": 11104, "name": "Salamander", "element": "Light" },
  { "com2us_id": 11101, "name": "Salamander", "element": "Water" },
  { "com2us_id": 40803, "name": "Salamander", "element": "Wind" },
  { "com2us_id": 11103, "name": "Salamander", "element": "Wind" },
  { "com2us_id": 12813, "name": "Samour", "element": "Wind" },
  { "com2us_id": 16905, "name": "Samurai", "element": "Dark" },
  { "com2us_id": 16902, "name": "Samurai", "element": "Fire" },
  { "com2us_id": 16904, "name": "Samurai", "element": "Light" },
  { "com2us_id": 16901, "name": "Samurai", "element": "Water" },
  { "com2us_id": 16903, "name": "Samurai", "element": "Wind" },
  { "com2us_id": 13105, "name": "Sandman", "element": "Dark" },
  { "com2us_id": 13102, "name": "Sandman", "element": "Fire" },
  { "com2us_id": 13101, "name": "Sandman", "element": "Water" },
  { "com2us_id": 13103, "name": "Sandman", "element": "Wind" },
  { "com2us_id": 16012, "name": "Sath", "element": "Fire" },
  { "com2us_id": 19705, "name": "Sea Emperor", "element": "Dark" },
  { "com2us_id": 19702, "name": "Sea Emperor", "element": "Fire" },
  { "com2us_id": 19704, "name": "Sea Emperor", "element": "Light" },
  { "com2us_id": 19701, "name": "Sea Emperor", "element": "Water" },
  { "com2us_id": 19703, "name": "Sea Emperor", "element": "Wind" },
  { "com2us_id": 12113, "name": "Seal", "element": "Wind" },
  { "com2us_id": 15713, "name": "Seara", "element": "Wind" },
  { "com2us_id": 20512, "name": "Sekhmet", "element": "Fire" },
  { "com2us_id": 13313, "name": "Selena", "element": "Wind" },
  { "com2us_id": 19311, "name": "Sera", "element": "Water" },
  { "com2us_id": 12115, "name": "Seren", "element": "Dark" },
  { "com2us_id": 11305, "name": "Serpent", "element": "Dark" },
  { "com2us_id": 11302, "name": "Serpent", "element": "Fire" },
  { "com2us_id": 11304, "name": "Serpent", "element": "Light" },
  { "com2us_id": 11301, "name": "Serpent", "element": "Water" },
  { "com2us_id": 11303, "name": "Serpent", "element": "Wind" },
  { "com2us_id": 15814, "name": "Shaffron", "element": "Light" },
  { "com2us_id": 11311, "name": "Shailoq", "element": "Water" },
  { "com2us_id": 21912, "name": "Shaina", "element": "Fire" },
  { "com2us_id": 14013, "name": "Shakan", "element": "Wind" },
  { "com2us_id": 11514, "name": "Shamann", "element": "Light" },
  { "com2us_id": 10614, "name": "Shamar", "element": "Light" },
  { "com2us_id": 14614, "name": "Shan", "element": "Light" },
  { "com2us_id": 10313, "name": "Shannon", "element": "Wind" },
  { "com2us_id": 11114, "name": "Sharman", "element": "Light" },
  { "com2us_id": 15411, "name": "Sharron", "element": "Water" },
  { "com2us_id": 17414, "name": "Shazam", "element": "Light" },
  { "com2us_id": 16811, "name": "Shi Hou", "element": "Water" },
  { "com2us_id": 11212, "name": "Shihwa", "element": "Fire" },
  { "com2us_id": 11813, "name": "Shimitae", "element": "Wind" },
  { "com2us_id": 12014, "name": "Shren", "element": "Light" },
  { "com2us_id": 10615, "name": "Shumar", "element": "Dark" },
  { "com2us_id": 13214, "name": "Shushu", "element": "Light" },
  { "com2us_id": 12114, "name": "Sia", "element": "Light" },
  { "com2us_id": 13411, "name": "Sian", "element": "Water" },
  { "com2us_id": 10612, "name": "Sieq", "element": "Fire" },
  { "com2us_id": 16915, "name": "Sige", "element": "Dark" },
  { "com2us_id": 14511, "name": "Sigmarus", "element": "Water" },
  { "com2us_id": 15913, "name": "Silia", "element": "Wind" },
  { "com2us_id": 16514, "name": "Silver", "element": "Light" },
  { "com2us_id": 20212, "name": "Sin", "element": "Fire" },
  { "com2us_id": 12111, "name": "Sisroo", "element": "Water" },
  { "com2us_id": 16402, "name": "Skull Soldier", "element": "Fire" },
  { "com2us_id": 16401, "name": "Skull Soldier", "element": "Water" },
  { "com2us_id": 16403, "name": "Skull Soldier", "element": "Wind" },
  { "com2us_id": 18305, "name": "Sky Dancer", "element": "Dark" },
  { "com2us_id": 18302, "name": "Sky Dancer", "element": "Fire" },
  { "com2us_id": 18304, "name": "Sky Dancer", "element": "Light" },
  { "com2us_id": 18301, "name": "Sky Dancer", "element": "Water" },
  { "com2us_id": 18303, "name": "Sky Dancer", "element": "Wind" },
  { "com2us_id": 12202, "name": "Slime", "element": "Fire" },
  { "com2us_id": 12201, "name": "Slime", "element": "Water" },
  { "com2us_id": 12203, "name": "Slime", "element": "Wind" },
  { "com2us_id": 20712, "name": "Smokey", "element": "Fire" },
  { "com2us_id": 11211, "name": "Soha", "element": "Water" },
  { "com2us_id": 21411, "name": "Sonnet", "element": "Water" },
  { "com2us_id": 20312, "name": "Sonora", "element": "Fire" },
  { "com2us_id": 16815, "name": "Son Zhang Lao", "element": "Dark" },
  { "com2us_id": 13913, "name": "Sophia", "element": "Wind" },
  { "com2us_id": 10115, "name": "Sorin", "element": "Dark" },
  { "com2us_id": 11512, "name": "Spectra", "element": "Fire" },
  { "com2us_id": 19911, "name": "Stella", "element": "Water" },
  { "com2us_id": 15511, "name": "Su", "element": "Water" },
  { "com2us_id": 13305, "name": "Succubus", "element": "Dark" },
  { "com2us_id": 13302, "name": "Succubus", "element": "Fire" },
  { "com2us_id": 13304, "name": "Succubus", "element": "Light" },
  { "com2us_id": 13301, "name": "Succubus", "element": "Water" },
  { "com2us_id": 13303, "name": "Succubus", "element": "Wind" },
  { "com2us_id": 21714, "name": "Super Angelmon", "element": "Light" },
  { "com2us_id": 18513, "name": "Suri", "element": "Wind" },
  { "com2us_id": 13605, "name": "Surprise Box", "element": "Dark" },
  { "com2us_id": 13602, "name": "Surprise Box", "element": "Fire" },
  { "com2us_id": 13604, "name": "Surprise Box", "element": "Light" },
  { "com2us_id": 13601, "name": "Surprise Box", "element": "Water" },
  { "com2us_id": 13603, "name": "Surprise Box", "element": "Wind" },
  { "com2us_id": 18812, "name": "Surtr", "element": "Fire" },
  { "com2us_id": 13511, "name": "Susano", "element": "Water" },
  { "com2us_id": 11805, "name": "Sylph", "element": "Dark" },
  { "com2us_id": 11802, "name": "Sylph", "element": "Fire" },
  { "com2us_id": 11804, "name": "Sylph", "element": "Light" },
  { "com2us_id": 11801, "name": "Sylph", "element": "Water" },
  { "com2us_id": 40903, "name": "Sylph", "element": "Wind" },
  { "com2us_id": 11803, "name": "Sylph", "element": "Wind" },
  { "com2us_id": 11905, "name": "Sylphid", "element": "Dark" },
  { "com2us_id": 11902, "name": "Sylphid", "element": "Fire" },
  { "com2us_id": 11904, "name": "Sylphid", "element": "Light" },
  { "com2us_id": 11901, "name": "Sylphid", "element": "Water" },
  { "com2us_id": 40403, "name": "Sylphid", "element": "Wind" },
  { "com2us_id": 11903, "name": "Sylphid", "element": "Wind" },
  { "com2us_id": 20115, "name": "Sylvia", "element": "Dark" },
  { "com2us_id": 21314, "name": "Tablo", "element": "Light" },
  { "com2us_id": 11712, "name": "Tagaros", "element": "Fire" },
  { "com2us_id": 10813, "name": "Taharus", "element": "Wind" },
  { "com2us_id": 19011, "name": "Talc", "element": "Water" },
  { "com2us_id": 21911, "name": "Talia", "element": "Water" },
  { "com2us_id": 10412, "name": "Tantra", "element": "Fire" },
  { "com2us_id": 19913, "name": "Tanya", "element": "Wind" },
  { "com2us_id": 18405, "name": "Taoist", "element": "Dark" },
  { "com2us_id": 18402, "name": "Taoist", "element": "Fire" },
  { "com2us_id": 18404, "name": "Taoist", "element": "Light" },
  { "com2us_id": 18401, "name": "Taoist", "element": "Water" },
  { "com2us_id": 18403, "name": "Taoist", "element": "Wind" },
  { "com2us_id": 14611, "name": "Taor", "element": "Water" },
  { "com2us_id": 310106, "name": "Taotie" },
  { "com2us_id": 22213, "name": "Taranys", "element": "Wind" },
  { "com2us_id": 22313, "name": "Taranys", "element": "Wind" },
  { "com2us_id": 10611, "name": "Tarq", "element": "Water" },
  { "com2us_id": 46001, "name": "Tartarus" },
  { "com2us_id": 10214, "name": "Taru", "element": "Light" },
  { "com2us_id": 10312, "name": "Tatu", "element": "Fire" },
  { "com2us_id": 18113, "name": "Taurus", "element": "Wind" },
  { "com2us_id": 10914, "name": "Teon", "element": "Light" },
  { "com2us_id": 17112, "name": "Tesarion", "element": "Fire" },
  { "com2us_id": 19212, "name": "Tesarion", "element": "Fire" },
  { "com2us_id": 14513, "name": "Teshar", "element": "Wind" },
  { "com2us_id": 19611, "name": "Tetra", "element": "Water" },
  { "com2us_id": 20415, "name": "Thebae", "element": "Dark" },
  { "com2us_id": 17111, "name": "Theomars", "element": "Water" },
  { "com2us_id": 19211, "name": "Theomars", "element": "Water" },
  { "com2us_id": 16015, "name": "Thrain", "element": "Dark" },
  { "com2us_id": 18913, "name": "Tiana", "element": "Wind" },
  { "com2us_id": 21214, "name": "Tian Lang", "element": "Light" },
  { "com2us_id": 17214, "name": "Tien Qin", "element": "Light" },
  { "com2us_id": 12811, "name": "Tigresse", "element": "Water" },
  { "com2us_id": 11615, "name": "Tilasha", "element": "Dark" },
  { "com2us_id": 18711, "name": "Toma", "element": "Water" },
  { "com2us_id": 16914, "name": "Tosi", "element": "Light" },
  { "com2us_id": 20811, "name": "Tractor", "element": "Water" },
  { "com2us_id": 20012, "name": "Trevor", "element": "Fire" },
  { "com2us_id": 21413, "name": "Triana", "element": "Wind" },
  { "com2us_id": 13815, "name": "Trinity", "element": "Dark" },
  { "com2us_id": 19713, "name": "Triton", "element": "Wind" },
  { "com2us_id": 310206, "name": "Turtle" },
  { "com2us_id": 11811, "name": "Tyron", "element": "Water" },
  { "com2us_id": 11605, "name": "Undine", "element": "Dark" },
  { "com2us_id": 11602, "name": "Undine", "element": "Fire" },
  { "com2us_id": 11604, "name": "Undine", "element": "Light" },
  { "com2us_id": 11601, "name": "Undine", "element": "Water" },
  { "com2us_id": 40501, "name": "Undine", "element": "Water" },
  { "com2us_id": 11603, "name": "Undine", "element": "Wind" },
  { "com2us_id": 21505, "name": "Unicorn", "element": "Dark" },
  { "com2us_id": 21502, "name": "Unicorn", "element": "Fire" },
  { "com2us_id": 21504, "name": "Unicorn", "element": "Light" },
  { "com2us_id": 21501, "name": "Unicorn", "element": "Water" },
  { "com2us_id": 21503, "name": "Unicorn", "element": "Wind" },
  { "com2us_id": 10712, "name": "Ursha", "element": "Fire" },
  { "com2us_id": 17711, "name": "Urtau", "element": "Water" },
  { "com2us_id": 15205, "name": "Vagabond", "element": "Dark" },
  { "com2us_id": 15202, "name": "Vagabond", "element": "Fire" },
  { "com2us_id": 15204, "name": "Vagabond", "element": "Light" },
  { "com2us_id": 15201, "name": "Vagabond", "element": "Water" },
  { "com2us_id": 15203, "name": "Vagabond", "element": "Wind" },
  { "com2us_id": 22214, "name": "Valantis", "element": "Light" },
  { "com2us_id": 22314, "name": "Valantis", "element": "Light" },
  { "com2us_id": 13805, "name": "Valkyrja", "element": "Dark" },
  { "com2us_id": 13802, "name": "Valkyrja", "element": "Fire" },
  { "com2us_id": 13804, "name": "Valkyrja", "element": "Light" },
  { "com2us_id": 13801, "name": "Valkyrja", "element": "Water" },
  { "com2us_id": 13803, "name": "Valkyrja", "element": "Wind" },
  { "com2us_id": 14705, "name": "Vampire", "element": "Dark" },
  { "com2us_id": 14702, "name": "Vampire", "element": "Fire" },
  { "com2us_id": 14704, "name": "Vampire", "element": "Light" },
  { "com2us_id": 14701, "name": "Vampire", "element": "Water" },
  { "com2us_id": 14703, "name": "Vampire", "element": "Wind" },
  { "com2us_id": 13812, "name": "Vanessa", "element": "Fire" },
  { "com2us_id": 12814, "name": "Varis", "element": "Light" },
  { "com2us_id": 11515, "name": "Varus", "element": "Dark" },
  { "com2us_id": 17012, "name": "Velajuel", "element": "Fire" },
  { "com2us_id": 17813, "name": "Velfinodon", "element": "Wind" },
  { "com2us_id": 14411, "name": "Verad", "element": "Water" },
  { "com2us_id": 14712, "name": "Verdehile", "element": "Fire" },
  { "com2us_id": 17115, "name": "Veromos", "element": "Dark" },
  { "com2us_id": 19215, "name": "Veromos", "element": "Dark" },
  { "com2us_id": 14011, "name": "Vigor", "element": "Water" },
  { "com2us_id": 14805, "name": "Viking", "element": "Dark" },
  { "com2us_id": 14802, "name": "Viking", "element": "Fire" },
  { "com2us_id": 14804, "name": "Viking", "element": "Light" },
  { "com2us_id": 14801, "name": "Viking", "element": "Water" },
  { "com2us_id": 14803, "name": "Viking", "element": "Wind" },
  { "com2us_id": 21415, "name": "Vivachel", "element": "Dark" },
  { "com2us_id": 15614, "name": "Walkers", "element": "Light" },
  { "com2us_id": 14813, "name": "Walter", "element": "Wind" },
  { "com2us_id": 10705, "name": "Warbear", "element": "Dark" },
  { "com2us_id": 10702, "name": "Warbear", "element": "Fire" },
  { "com2us_id": 10704, "name": "Warbear", "element": "Light" },
  { "com2us_id": 10701, "name": "Warbear", "element": "Water" },
  { "com2us_id": 10703, "name": "Warbear", "element": "Wind" },
  { "com2us_id": 60101, "name": "Water Guardian", "element": "Water" },
  { "com2us_id": 15611, "name": "Wayne", "element": "Water" },
  { "com2us_id": 20614, "name": "Wedjat", "element": "Light" },
  { "com2us_id": 17215, "name": "Wei Shin", "element": "Dark" },
  { "com2us_id": 14005, "name": "Werewolf", "element": "Dark" },
  { "com2us_id": 14002, "name": "Werewolf", "element": "Fire" },
  { "com2us_id": 14004, "name": "Werewolf", "element": "Light" },
  { "com2us_id": 14001, "name": "Werewolf", "element": "Water" },
  { "com2us_id": 14003, "name": "Werewolf", "element": "Wind" },
  { "com2us_id": 14214, "name": "White Angelmon", "element": "Light" },
  { "com2us_id": 18214, "name": "White King Angelmon", "element": "Light" },
  { "com2us_id": 43003, "name": "Wind Beast", "element": "Wind" },
  { "com2us_id": 60103, "name": "Wind Guardian", "element": "Wind" },
  { "com2us_id": 20713, "name": "Windy", "element": "Wind" },
  { "com2us_id": 18315, "name": "Wolyung", "element": "Dark" },
  { "com2us_id": 18413, "name": "Woochi", "element": "Wind" },
  { "com2us_id": 18415, "name": "Woonhak", "element": "Dark" },
  { "com2us_id": 18615, "name": "Woonsa", "element": "Dark" },
  { "com2us_id": 18611, "name": "Woosa", "element": "Water" },
  { "com2us_id": 17212, "name": "Xiao Chun", "element": "Fire" },
  { "com2us_id": 17311, "name": "Xiao Lin", "element": "Water" },
  { "com2us_id": 15014, "name": "Xiao Ling", "element": "Light" },
  { "com2us_id": 16813, "name": "Xing Zhe", "element": "Wind" },
  { "com2us_id": 21212, "name": "Xiong Fei", "element": "Fire" },
  { "com2us_id": 15811, "name": "Yaku", "element": "Water" },
  { "com2us_id": 15513, "name": "Yen", "element": "Wind" },
  { "com2us_id": 18314, "name": "Yeonhong", "element": "Light" },
  { "com2us_id": 10405, "name": "Yeti", "element": "Dark" },
  { "com2us_id": 10402, "name": "Yeti", "element": "Fire" },
  { "com2us_id": 10404, "name": "Yeti", "element": "Light" },
  { "com2us_id": 10401, "name": "Yeti", "element": "Water" },
  { "com2us_id": 10403, "name": "Yeti", "element": "Wind" },
  { "com2us_id": 14412, "name": "Zaiross", "element": "Fire" },
  { "com2us_id": 22013, "name": "Zenobia", "element": "Wind" },
  { "com2us_id": 19513, "name": "Zephicus", "element": "Wind" },
  { "com2us_id": 14414, "name": "Zerath", "element": "Light" },
  { "com2us_id": 14615, "name": "Zeratu", "element": "Dark" },
  { "com2us_id": 18112, "name": "Zibrolta", "element": "Fire" },
  { "com2us_id": 16515, "name": "Zinc", "element": "Dark" },
]